In [14]:
# MNIST 데이터를 다운로드 한다.
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True) # [0,0,1,0,...,0,0]

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [15]:
# TensorFlow 라이브러리를 추가한다.
import tensorflow as tf
import numpy as np

In [16]:
# function for printing tensor
def print_tensor(x):
  init = tf.global_variables_initializer()
  with tf.Session() as sess:
    init.run()
    result=x.eval()
    print(result)

def print_place_holder(input, a, b):
  init = tf.global_variables_initializer()
  with tf.Session() as sess:
    init.run()
    result = sess.run(input, feed_dict={x: a, y_: b})
    print(result)

In [17]:
 # 변수들을 설정한다.
image_size = 28*28                                 
x = tf.placeholder(tf.float32, [None, image_size])

W = tf.Variable(tf.zeros([image_size, 10]))
b = tf.Variable(tf.zeros([10]))
y = tf.nn.softmax(tf.matmul(x, W) + b)
# y_: true label
y_ = tf.placeholder(tf.float32, [None, 10])
print_place_holder(x, mnist.train.images[0:5], mnist.train.labels[0:5])

[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]


In [18]:
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "https://oakmachine.com/img/multinomial-logistic-classification-diagram.png")

In [19]:
from IPython.display import Image
from IPython.core.display import HTML 
Image(url= "http://cfile29.uf.tistory.com/image/2153C64F5797F9C32E9735")

In [20]:
# cross-entropy 모델을 설정한다.
# y = logit
# -tf.reduce_sum(y_ * tf.log(y), reduction_indices=[1]) = softmax_cross_entropy_with_logits in tf
cross_entropy = tf.reduce_mean(-tf.reduce_sum(y_ * tf.log(y), reduction_indices=[1]))
print_place_holder(-tf.reduce_sum(y_ * tf.log(y), reduction_indices=[1]), \
                   mnist.train.images[0:5], mnist.train.labels[0:5])
train_step = tf.train.GradientDescentOptimizer(0.5).minimize(cross_entropy)

[ 2.30258512  2.30258512  2.30258512  2.30258512  2.30258512]


In [21]:
# 경사하강법으로 모델을 학습한다.
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
for i in range(1000):
  batch_xs, batch_ys = mnist.train.next_batch(100)
  sess.run(train_step, feed_dict={x: batch_xs, y_: batch_ys})

In [24]:
# 학습된 모델이 얼마나 정확한지를 출력한다.
# 1 x 10 o(Wx+b)
print_place_holder(y, mnist.train.images[0:1], mnist.train.labels[0:1])
print_place_holder(tf.argmax(y,1), mnist.train.images[0:1], mnist.train.labels[0:1])

[[ 0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1]]
[0]


In [25]:
# 1 x 10 y
print_place_holder(y_, mnist.train.images[0:1], mnist.train.labels[0:1])
print_place_holder(tf.argmax(y_,1), mnist.train.images[0:1], mnist.train.labels[0:1])

[[ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]]
[2]


In [26]:
correct_prediction = tf.equal(tf.argmax(y,1), tf.argmax(y_,1))
print_place_holder(correct_prediction, mnist.train.images[0:1], mnist.train.labels[0:1])

[False]


In [23]:
#[True, false] -> [1, 0]
# [0., 0. , 1. , ...]
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print_place_holder(tf.cast(correct_prediction, tf.float32), \
                   mnist.train.images[0:1], mnist.train.labels[0:1])

print(sess.run(accuracy, feed_dict={x: mnist.test.images, y_: mnist.test.labels}))

[ 0.]
0.9188
