### 연습 문제 2-1

#### 벡터 x가 다음과 같을 때, 여러가지 수식을 사용하여 같은 크기의 벡터 y를 만드세요.
##### 예시) x + 10

In [2]:
import numpy as np

x = np.arange(10)

In [2]:
x + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [3]:
x * 10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [4]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [5]:
10 ** x

array([         1,         10,        100,       1000,      10000,
           100000,    1000000,   10000000,  100000000, 1000000000])

In [6]:
y = np.zeros_like(x)

x == y

array([ True, False, False, False, False, False, False, False, False,
       False])

In [7]:
x - y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 연습 문제 2-2

#### 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.
1. 전체의 최댓값
2. 각 행의 합
3. 각 열의 평균

In [24]:
arr = np.random.randint(30, size=(5, 6))
arr

array([[14, 10, 21,  1, 10, 12],
       [24, 10, 29, 24, 19, 20],
       [ 4, 25,  7, 21, 11, 17],
       [ 2, 25,  7, 22,  2,  2],
       [13, 27, 20,  2,  0, 21]])

In [5]:
np.max(arr) # 1.전체의 최댓값

29

In [31]:
arr.sum(axis=1) # 2.각 행의 합

array([ 67,  24, 120, 180, 240])

In [32]:
arr.mean(axis=0) # 3.각 열의 평균

array([ 23.2,  19. ,  19.4,  21. ,  22. ,  21.6])

### 연습 문제 2-3

#### 연습 문제 2-2에서 만든 데이터에 대해 다음을 구한다.
1. 첫번째 열 값으로 모든 행을 정렬
2. 두번째 행 값으로 모든 열을 정렬

In [33]:
arr

array([[22,  3,  6,  9, 12, 15],
       [ 4,  2,  1,  6,  8,  3],
       [20, 20, 20, 20, 20, 20],
       [30, 30, 30, 30, 30, 30],
       [40, 40, 40, 40, 40, 40]])

In [25]:
arr[np.argsort(arr[:,0])] # 1.첫번째 열 값으로 모든 행을 정렬

array([[ 2, 25,  7, 22,  2,  2],
       [ 4, 25,  7, 21, 11, 17],
       [13, 27, 20,  2,  0, 21],
       [14, 10, 21,  1, 10, 12],
       [24, 10, 29, 24, 19, 20]])

In [26]:
arr[:5, np.argsort(arr[1,:])] # 2.두번째 행 값으로 모든 열을 정렬

array([[10, 10, 12, 14,  1, 21],
       [10, 19, 20, 24, 24, 29],
       [25, 11, 17,  4, 21,  7],
       [25,  2,  2,  2, 22,  7],
       [27,  0, 21, 13,  2, 20]])